FROM python:3.7-slim

RUN apt-get update &&  apt-get install -y wget libgl1 libglib2.0-0 libgssapi-krb5-2 && \
    apt-get install -y locales && sed -i -e 's/# ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/' /etc/locale.gen &&  dpkg-reconfigure --frontend=noninteractive locales && update-locale LANG=ru_RU.UTF-8 && \
    apt-get install -y  build-essential ffmpeg  && \
    rm -rf /var/lib/apt/lists/* && \
    wget -O requirements.txt   https://server1.rndnet.net/static/simple/rndnet-scheduler/requirements.txt && \
    pip install $(cat /requirements.txt | grep -iv pyqt | grep -v qscintilla) pyqt5 && \
    pip install --index-url https://server1.rndnet.net/static/simple bfj && \
    pip install --index-url https://server1.rndnet.net/static/simple rndnet-scheduler && \
    pip install scipy audio2numpy cvxpy DateTime ecos imageio matplotlib numpy pandas Pillow sympy windrose sklearn lxml tqdm xlrd pydicom minio

#ENTRYPOINT ["rndnet_scheduler", "--sched", "mp", "--pgpkey", "/opt/rndnet/secret.key"]

